/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumIndexRouteImport } from './routes/album.index'
import { Route as AlbumTimelineRouteImport } from './routes/album.timeline'
import { Route as AlbumFavoritesRouteImport } from './routes/album.favorites'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AlbumCSlugRouteImport } from './routes/album.c.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedMyChaptersIndexRouteImport } from './routes/_authenticated/my.chapters.index'
import { Route as AuthenticatedAdminChaptersIndexRouteImport } from './routes/_authenticated/admin.chapters.index'
import { Route as AuthenticatedChaptersIdEditRouteImport } from './routes/_authenticated/chapters.$id.edit'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIndexRoute = AlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumTimelineRoute = AlbumTimelineRouteImport.update({
  id: '/album/timeline',
  path: '/album/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumFavoritesRoute = AlbumFavoritesRouteImport.update({
  id: '/album/favorites',
  path: '/album/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AlbumCSlugRoute = AlbumCSlugRouteImport.update({
  id: '/album/c/$slug',
  path: '/album/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyChaptersIndexRoute =
  AuthenticatedMyChaptersIndexRouteImport.update({
    id: '/my/chapters/',
    path: '/my/chapters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminChaptersIndexRoute =
  AuthenticatedAdminChaptersIndexRouteImport.update({
    id: '/admin/chapters/',
    path: '/admin/chapters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChaptersIdEditRoute =
  AuthenticatedChaptersIdEditRouteImport.update({
    id: '/chapters/$id/edit',
    path: '/chapters/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/album/favorites': typeof AlbumFavoritesRoute
  '/album/timeline': typeof AlbumTimelineRoute
  '/album/': typeof AlbumIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/album/c/$slug': typeof AlbumCSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/chapters/$id/edit': typeof AuthenticatedChaptersIdEditRoute
  '/admin/chapters/': typeof AuthenticatedAdminChaptersIndexRoute
  '/my/chapters/': typeof AuthenticatedMyChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/album/favorites': typeof AlbumFavoritesRoute
  '/album/timeline': typeof AlbumTimelineRoute
  '/album': typeof AlbumIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/album/c/$slug': typeof AlbumCSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/chapters/$id/edit': typeof AuthenticatedChaptersIdEditRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersIndexRoute
  '/my/chapters': typeof AuthenticatedMyChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/album/favorites': typeof AlbumFavoritesRoute
  '/album/timeline': typeof AlbumTimelineRoute
  '/album/': typeof AlbumIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/album/c/$slug': typeof AlbumCSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/chapters/$id/edit': typeof AuthenticatedChaptersIdEditRoute
  '/_authenticated/admin/chapters/': typeof AuthenticatedAdminChaptersIndexRoute
  '/_authenticated/my/chapters/': typeof AuthenticatedMyChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/album/favorites'
    | '/album/timeline'
    | '/album/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/album/c/$slug'
    | '/admin/'
    | '/chapters/$id/edit'
    | '/admin/chapters/'
    | '/my/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/album/favorites'
    | '/album/timeline'
    | '/album'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/album/c/$slug'
    | '/admin'
    | '/chapters/$id/edit'
    | '/admin/chapters'
    | '/my/chapters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/map'
    | '/mcp'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/album/favorites'
    | '/album/timeline'
    | '/album/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/album/c/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/chapters/$id/edit'
    | '/_authenticated/admin/chapters/'
    | '/_authenticated/my/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  UnlockRoute: typeof UnlockRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AlbumFavoritesRoute: typeof AlbumFavoritesRoute
  AlbumTimelineRoute: typeof AlbumTimelineRoute
  AlbumIndexRoute: typeof AlbumIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AlbumCSlugRoute: typeof AlbumCSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/': {
      id: '/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AlbumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/timeline': {
      id: '/album/timeline'
      path: '/album/timeline'
      fullPath: '/album/timeline'
      preLoaderRoute: typeof AlbumTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/favorites': {
      id: '/album/favorites'
      path: '/album/favorites'
      fullPath: '/album/favorites'
      preLoaderRoute: typeof AlbumFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/album/c/$slug': {
      id: '/album/c/$slug'
      path: '/album/c/$slug'
      fullPath: '/album/c/$slug'
      preLoaderRoute: typeof AlbumCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my/chapters/': {
      id: '/_authenticated/my/chapters/'
      path: '/my/chapters'
      fullPath: '/my/chapters/'
      preLoaderRoute: typeof AuthenticatedMyChaptersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/chapters/': {
      id: '/_authenticated/admin/chapters/'
      path: '/admin/chapters'
      fullPath: '/admin/chapters/'
      preLoaderRoute: typeof AuthenticatedAdminChaptersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chapters/$id/edit': {
      id: '/_authenticated/chapters/$id/edit'
      path: '/chapters/$id/edit'
      fullPath: '/chapters/$id/edit'
      preLoaderRoute: typeof AuthenticatedChaptersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedChaptersIdEditRoute: typeof AuthenticatedChaptersIdEditRoute
  AuthenticatedAdminChaptersIndexRoute: typeof AuthenticatedAdminChaptersIndexRoute
  AuthenticatedMyChaptersIndexRoute: typeof AuthenticatedMyChaptersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedChaptersIdEditRoute: AuthenticatedChaptersIdEditRoute,
  AuthenticatedAdminChaptersIndexRoute: AuthenticatedAdminChaptersIndexRoute,
  AuthenticatedMyChaptersIndexRoute: AuthenticatedMyChaptersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  UnlockRoute: UnlockRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AlbumFavoritesRoute: AlbumFavoritesRoute,
  AlbumTimelineRoute: AlbumTimelineRoute,
  AlbumIndexRoute: AlbumIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AlbumCSlugRoute: AlbumCSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
